### ISSUE TITLE
Aggiornate per macOS (Importante)

### ISSUE THREAD

**Issue by SiNaPsEr0x** [c137ricksanchez/automatic-releaser#10]
salve allora ho fixato a mano ... togliete il limite == a scipy perchè su mac nuovo altrimenti non funziona

dopo di che su mac bisogna installare PRIMA `brew install meson-python  scipy` e dopo di che fare tutto come da guida

**Comment by Norman2034** [comment]
Ciao, il commit https://github.com/c137ricksanchez/automatic-releaser/commit/8c3009d1cc285564e6ba57d881a03f5ee78d6c46 risolve il problema.
Semplicemente usavamo una versione di scipy incompatibile con Python 3.12.
